export const queryKeys = {
  session: ["session"] as const,
  appConfig: ["config", "app"] as const,
  authConfig: ["config", "auth"] as const,
  navigation: ["config", "navigation"] as const,
  permissions: ["config", "permissions"] as const,
  workflows: ["config", "workflows"] as const,
  dictionaries: ["config", "dictionaries"] as const,
  categories: ["categories"] as const,
  brands: ["brands"] as const,
  products: ["products"] as const,
  inventory: ["inventory"] as const,
  orders: ["orders"] as const,
  customers: ["customers"] as const,
  repairs: ["repairs"] as const,
  employees: ["employees"] as const,
  settings: ["settings"] as const,
  finance: ["finance"] as const,
  activity: ["activity"] as const,
  clientMe: ["client", "me"] as const,
  clientProducts: ["client", "products"] as const,
  clientOrders: ["client", "orders"] as const,
  clientRepairs: ["client", "repairs"] as const,
  dashboard: ["page", "dashboard"] as const,
  clientHome: ["page", "client-home"] as const,
  catalog: ["page", "catalog"] as const,
  clientCatalog: ["page", "client-catalog"] as const,
  inventoryPage: ["page", "inventory"] as const,
  adminOrdersPage: ["page", "orders", "admin"] as const,
  clientOrdersPage: ["page", "orders", "client"] as const,
  customersPage: ["page", "customers"] as const,
  clientRepairsPage: ["page", "repairs", "client"] as const,
  settingsPage: ["page", "settings"] as const,
  employeesPage: ["page", "employees"] as const,
  financePage: ["page", "finance"] as const,
  mediaPage: ["page", "media"] as const,
  storefrontCatalog: ["page", "storefront", "catalog"] as const,
  storefrontProduct: ["page", "storefront", "product"] as const,
};
